import {scenarios,viewportSpecs,designFilename} from './scenarios.mjs?v=page-stage-01';
const area=document.getElementById('review-content');
const descriptions={A:['初遇与选猫','选择只更新当前外观；点“继续”才进入起名。完整复用 CatSelectionCard V1，保留角色短描述与“想认识它”。页面自然向下滚动。'],B:['给它起个名字','输入保留草稿，中文与表情按可见字符计数。键盘稿为布局示意，非真机复拍。'],C:['最后，再确认一次','完整展示领养规则。提交锁定、明确失败可重试，结果未知仅允许读取，已确认不再改选。']};
function sampleUrl(id){return `index.html?scene=${id}`;}
function stage(page){const d=descriptions[page];const list=scenarios.filter(s=>s.page===page);const first=list[0];return `<div class="review-stage"><aside class="stage-info"><h2>${d[0]}</h2><p>${d[1]}</p><div class="state-buttons">${list.map((s,i)=>`<button data-scene="${s.id}" aria-pressed="${i===0}">${s.label}</button>`).join('')}</div><a class="direct-link" id="open-sample" href="${sampleUrl(first.id)}" target="_blank" rel="noopener">单独打开当前样例 →</a></aside><div><div class="device-wrap"><iframe class="device" title="${d[0]}交互样例" src="${sampleUrl(first.id)}"></iframe></div><p class="stage-caption">基准 M · 390 × 844；窄屏审阅区随容器适配</p></div></div>`;}
function gallery(){return `<h2 class="board-title">关键状态，一页核对</h2><p class="responsive-note">每张状态稿均可点击打开交互样例；键盘稿包含明确标记的占位示意。</p><div class="state-gallery">${scenarios.map(s=>`<figure class="state-figure"><a href="${sampleUrl(s.id)}" target="_blank" rel="noopener"><img src="designs/${designFilename(s.id)}" alt="UI-01${s.page} ${s.label}状态稿" loading="lazy"><figcaption>UI-01${s.page} · ${s.label}<small>M · 390px 宽，长页自然延展</small></figcaption></a></figure>`).join('')}</div>`;}
function responsive(){return `<h2 class="board-title">从紧凑手机到桌面</h2><p class="responsive-note">手机保持双列选择；桌面主体最大 620px，内部左右 28px。以下为实际视口导出。</p><div class="view-buttons">${viewportSpecs.map((v,i)=>`<button data-size="${v.id}" aria-pressed="${i===0}">${v.id} · ${v.width} × ${v.height}</button>`).join('')}</div><div class="responsive-frames" id="responsive-frames"></div><a class="direct-link" href="index.html?scene=C-ready&text=200" target="_blank" rel="noopener">查看 200% 字号确认页 →</a>`;}
function showSize(size){area.querySelectorAll('[data-size]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.size===size)));document.getElementById('responsive-frames').innerHTML=['A-selected','C-ready'].map(id=>`<section><h3>UI-01${id[0]} · ${size}</h3><a href="designs/${designFilename(id,size)}" target="_blank" rel="noopener"><img src="designs/${designFilename(id,size)}" alt="UI-01${id[0]} ${size}响应式稿"></a></section>`).join('');}
function render(view){if(!['A','B','C','states','responsive'].includes(view))view='A';document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));area.innerHTML=descriptions[view]?stage(view):view==='states'?gallery():responsive();if(view==='responsive')showSize('M');history.replaceState(null,'','#'+view);}
document.addEventListener('click',e=>{const nav=e.target.closest('[data-view]');if(nav){render(nav.dataset.view);return;}const s=e.target.closest('[data-scene]');if(s){area.querySelector('iframe').src=sampleUrl(s.dataset.scene);area.querySelectorAll('[data-scene]').forEach(b=>b.setAttribute('aria-pressed',String(b===s)));document.getElementById('open-sample').href=sampleUrl(s.dataset.scene);}const v=e.target.closest('[data-size]');if(v)showSize(v.dataset.size);});
render(location.hash.slice(1));
