import {needCard,replyInput,updateReplyInputState,focusReply,icon,escapeHtml as e,homeNavigation,newLetterEntry} from '../ui-components-v1/daily-components.mjs';
import {initialState,transition,currentLetter,getHomeEntry,LETTER_FIXTURES,canSubmit} from './daily-state.mjs';
import {createDailyStore,STORAGE_KEY} from './storage.mjs';
import {buildScenario,SCENARIOS} from './scenarios.mjs';
const params=new URLSearchParams(location.search), app=document.querySelector('#app');
const scenarioId=params.get('scenario'), fixture=scenarioId&&SCENARIOS.some(s=>s.id===scenarioId)?buildScenario(scenarioId,{catId:params.get('cat')||'cat-01'}):null;
let ui=fixture?.ui||{}, failures=fixture?.failFixtures||{},store=createDailyStore({storage:fixture?.storageAdapter,failFixtures:failures});
let state=fixture?.state||store.load().state, saveTimer,sendTimer,composing=false,externalChange=false,saveFailure=false;
const restored=currentLetter(state)?.draftSaveState==='SAVED'&&!!currentLetter(state)?.draft;
if(!fixture&&restored)ui.draftRestored=true;
if(params.get('textScale')==='200')document.documentElement.dataset.textScale='200';
const arrow=()=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="m14 6-6 6 6 6"/></svg>';
const bodyById={'need-01':'窗边的小光点，刚才还在我的爪子旁边。\n我一眨眼，它就跑远了。\n明天它还会来吗？','need-02':'窗外又下起雨了。\n我把爪子缩进软软的毯子里，听见雨滴轻轻敲着玻璃。\n你那边，也在下雨吗？'};
function scenePath(){return `./assets/V1-${state.catState==='TRIP'?'travel-path':'home-window'}-${state.appearanceId}${state.catState==='HOME'&&state.appearanceId==='cat-03'?'-V1':''}.png`;}
function backButton(){return `<button type="button" class="quiet-link back-button" data-action="home">${arrow()}回到${e(state.catName)}身边</button>`;}
function scene(){return `<div class="scene" id="home-scene">${ui.imageError?`<div class="scene-fallback"><p>图片暂时没能加载。</p><button class="secondary" data-action="retry-image">再试一次</button></div>`:`<img src="${scenePath()}" alt="${e(state.catName)}${state.catState==='HOME'?'在窗边追光':'走在旅行的路上'}" width="1536" height="1024">`}</div>`;}
function home(){const trip=state.catState==='TRIP',entry=getHomeEntry(state);return `<section class="daily-page home-page"><header class="page-top"><span class="wordmark">有猫来信</span><button class="quiet-link" data-action="history">回看来信 <span aria-hidden="true">↗</span></button></header><div class="home-content"><div class="home-heading"><h1>${e(state.catName)}</h1><span class="cat-status${trip?' trip':''}">${trip?'旅行中':'在家'}</span></div>${ui.loading?'<div class="neutral-loading" role="status">正在读取本机记录…</div>':state.loadError?`<section class="error-block" role="status"><h2>暂时没能读取本机记录</h2><p>可以再试一次。</p><button class="secondary" data-action="retry-load">重新读取</button></section>`:`${scene()}<div class="life-copy"><h2>${trip?`${e(state.catName)}出去旅行啦。`:`${e(state.catName)}正在窗边追一块光。`}</h2>${trip?'<p>它什么时候寄信回来？不知道呢。</p>':''}</div>${entry?newLetterEntry({type:entry.type,unread:true}):'<div class="empty-letter">今天没有新来信。</div>'}`}<div data-slot="page-storage-error"></div></div>${homeNavigation({active:'cat',unread:!!entry})}</section>`;}
function replyOptions(){const letter=currentLetter(state);return {mode:'e3',id:'daily-reply',name:state.catName,value:letter?.draft||'',maxLength:2000,draftState:ui.draftRestored?'restored':state.draftSaveState.toLowerCase(),submitState:state.replySubmitState.toLowerCase(),systemState:state.checkState==='CHECK_ERROR'?'check-error':state.checkState==='SAFETY'?'blocked':'none',composing:composing||externalChange||state.loadError};}
function newMailNotice(){return state.newLetterId?'<aside class="new-mail-notice"><span>有一封新来信</span><button type="button" data-action="new-mail-home">回首页看看</button></aside>':'';}
function detail(){const l=currentLetter(state);return `<section class="daily-page detail-page"><header class="detail-top">${backButton()}</header><h1 class="detail-title">一封来信</h1><div data-slot="new-mail">${newMailNotice()}</div>${needCard({mode:'e3',catId:state.appearanceId,catName:state.catName,time:l.id==='need-02'?'今天 · 16:40':'今天 · 09:20',title:l.title,body:bodyById[l.id]||bodyById['need-01'],avatarUrl:`./assets/V1-cat-avatar-${state.appearanceId}.png`,replyTargetId:'daily-reply'})}<details class="tip-box"${ui.tipsOpen?' open':''}><summary>看看小提示</summary><p>可以说说你今天看见的一点小事，也可以只写一句话。<br>这次不想回，也没关系。</p></details><div data-slot="recovery">${recoveryNotice()}</div>${replyInput(replyOptions())}<button type="button" class="text-button skip" data-action="skip"${state.replySubmitState==='SUBMITTING'?' disabled':''}>这次先不回</button><div data-slot="page-storage-error"></div></section>`;}
function recoveryNotice(){if(state.loadError)return '<aside class="inline-notice page-banner" role="status"><strong>暂时没能读取本机记录。</strong><p>当前文字仍在这里，可以重新读取后再送出。</p><button class="secondary" data-action="retry-load">重新读取</button></aside>';return state.submissionRecoveryRequired?'<aside class="inline-notice page-banner" role="status"><strong>正在确认刚才的发送结果。</strong><p>文字仍在这里，先重新读取结果。</p><button class="secondary" data-action="recover">重新读取</button></aside>':'';}
function success(){return `<section class="daily-page success-page"><header class="page-top"><span class="wordmark">有猫来信</span></header><div class="success-content"><div class="success-panel">${icon('check')}<h1 class="story-title">送出去啦。</h1></div>${state.refreshError?'<aside class="inline-notice"><strong>回应已经送出。</strong><p>暂时没能读取最新状态，可以重新读取，也可以先回到小猫身边。</p><button class="secondary" data-action="retry-refresh">重新读取</button></aside>':''}${ui.reading?'<p class="local-notice" role="status">回应已经送出，正在读取最新状态…</p>':''}<button class="primary" data-action="home">回到${e(state.catName)}身边</button></div></section>`;}
function keyboard(){return '<aside class="keyboard-study" aria-label="键盘布局示意"><p>键盘展开 · 布局示意</p><div class="key-row">'+['Q','W','E','R','T','Y','U','I','O','P'].map(x=>`<span class="key">${x}</span>`).join('')+'</div><div class="key-row">'+['A','S','D','F','G','H','J','K','L'].map(x=>`<span class="key">${x}</span>`).join('')+'</div><div class="key-row">'+['⇧','Z','X','C','V','B','N','M','⌫'].map(x=>`<span class="key">${x}</span>`).join('')+'</div><div class="key-row"><span class="key">123</span><span class="key">◉</span><span class="key key-wide">空格</span><span class="key">换行</span></div></aside>';}
function render(){document.documentElement.dataset.page=state.page;document.body.classList.toggle('keyboard-layout',!!ui.keyboard&&state.page==='G');app.innerHTML=(['E','F'].includes(state.page)?home():state.page==='G'?detail():success())+(ui.keyboard&&state.page==='G'?keyboard():'');
 if(ui.reading){const retry=app.querySelector('[data-action="retry-refresh"]');if(retry)retry.disabled=true;} const img=app.querySelector('.scene img');if(img)img.addEventListener('error',()=>{ui.imageError=true;render();},{once:true});
 app.querySelectorAll('[data-action="home"],[data-action="skip"]').forEach(b=>b.disabled=state.replySubmitState==='SUBMITTING');
 const ta=app.querySelector('textarea');if(ta){ta.addEventListener('input',onInput);ta.addEventListener('compositionstart',()=>{composing=true;clearTimeout(saveTimer);patch();});ta.addEventListener('compositionend',()=>{composing=false;onInput();});growInput(ta);}
 if(ui.focus&&ta){ta.focus({preventScroll:true});ta.setSelectionRange(ta.value.length,ta.value.length);}
 if(ui.keyboard&&ta)requestAnimationFrame(()=>app.querySelector('.composer').scrollIntoView({block:'start',behavior:'instant'}));
 patch();notify();}
function growInput(ta){ta.style.height='auto';ta.style.height=Math.max(168,Math.min(360,ta.scrollHeight+2))+'px';}
function patch(){const form=app.querySelector('.composer');if(form)updateReplyInputState(form,replyOptions());const notice=app.querySelector('[data-slot="new-mail"]');if(notice)notice.innerHTML=newMailNotice();const recovery=app.querySelector('[data-slot="recovery"]');if(recovery)recovery.innerHTML=recoveryNotice();const slot=app.querySelector('[data-slot="page-storage-error"]');if(slot)slot.innerHTML=externalChange?'<aside class="inline-notice" role="status">另一个页面更新了本机记录。当前文字仍在这里。<button class="secondary" data-action="external-reload">重新读取</button></aside>':saveFailure?'<aside class="inline-notice" role="status">本机记录暂时没能保存，当前文字仍在这里。请保留此页面再试一次。<button class="secondary" data-action="retry-persist">重试保存</button></aside>':'';notify();}
function notify(){window.__dailyState=structuredClone(state);window.__dailyUI={...ui,externalChange,saveFailure};if(parent!==window)parent.postMessage({type:'daily-state',state:{page:state.page,catState:state.catState,newLetterId:state.newLetterId,currentLetterId:state.currentLetterId,draftSaveState:state.draftSaveState,replySubmitState:state.replySubmitState,letters:Object.values(state.letters).map(l=>({id:l.id,type:l.type,read:l.readState,draftLength:l.draft.length,reply:l.replySubmitState}))}},location.origin);}
function persist(){if(externalChange)return false;const r=store.persist(state);if(r.ok){state=r.state;saveFailure=false;}else{saveFailure=true;if(r.stale||r.conflict){externalChange=true;clearTimeout(sendTimer);clearTimeout(saveTimer);}}return r.ok;}
function apply(event,{paint=true,save=false}={}){state=transition(state,event);if(save)persist();if(paint)render();else patch();}
function onInput(){const ta=app.querySelector('textarea');if(!ta)return;ui.draftRestored=false;state=transition(state,{type:'EDIT',value:ta.value});growInput(ta);patch();clearTimeout(saveTimer);if(!composing&&!externalChange)saveTimer=setTimeout(()=>saveDraft(),550);}
function saveDraft(){clearTimeout(saveTimer);if(externalChange||composing||state.replySubmitState==='SUBMITTING'||state.replySubmitState==='SUCCESS')return false;const l=currentLetter(state);if(!l||l.draftSaveState==='SAVED'&&l.savedRevision===l.draftRevision)return true;state=transition(state,{type:'BEGIN_SAVE'});patch();const r=store.saveDraft(state);if(r.event)state=transition(state,r.event);if(r.stale){externalChange=true;const pending=state.pendingSave;if(pending)state=transition(state,{type:'SAVE_ERROR',...pending});}patch();return r.ok;}
function goHome(){if(state.replySubmitState==='SUBMITTING')return;if(state.page==='G'&&currentLetter(state)?.draft&&!saveDraft()){saveFailure=true;patch();return;}ui.draftRestored=false;ui.focus=false;apply({type:'BACK_HOME'},{save:true});window.scrollTo(0,0);}
function boundary(kind){const title=kind==='postcard'?'旅行明信片':kind==='history'?'历史来信':'来信盒';const dlg=document.createElement('dialog');dlg.className='review-boundary';dlg.innerHTML=`<h2>${title} · 审阅边界</h2><p>当前预览只覆盖首页、需求卡与回应、发送成功。${title}的完整页面将在第三批设计；关闭此说明后保留当前页面和未读状态。</p><button class="secondary">返回当前页面</button>`;document.body.append(dlg);dlg.querySelector('button').onclick=()=>dlg.close();dlg.addEventListener('close',()=>dlg.remove());dlg.showModal();}
async function submit(){if(externalChange||composing||!canSubmit(state))return;clearTimeout(saveTimer);state=transition(state,{type:'BEGIN_SUBMIT'});const ticket=state.pendingSubmission?.requestId;if(!ticket)return;if(!persist()){if(!externalChange)state=transition(state,{type:'SEND_ERROR',letterId:state.currentLetterId,requestId:ticket});patch();return;}patch();app.querySelectorAll('[data-action="home"],[data-action="skip"]').forEach(b=>b.disabled=true);sendTimer=setTimeout(()=>{if(externalChange||state.submissionRecoveryRequired||state.pendingSubmission?.requestId!==ticket)return;const r=store.commitReply(state);if(r.event)state=transition(state,r.event);render();if(state.page==='H')window.scrollTo(0,0);},850);}
app.addEventListener('submit',event=>{event.preventDefault();submit();});
app.addEventListener('click',event=>{const b=event.target.closest('[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;
 if(a==='focus-reply')focusReply(app,b.dataset.replyTarget);else if(a==='home'||a==='skip'||a==='new-mail-home')goHome();
 else if(a==='inbox'||a==='history')boundary(a);
 else if(a==='open-letter'){const l=getHomeEntry(state);if(!l)return;if(l.type==='POSTCARD')boundary('postcard');else{ui.draftRestored=false;ui.focus=false;apply({type:'OPEN_NEED',letterId:l.id},{save:true});window.scrollTo(0,0);}}
 else if(a==='retry-image'){ui.imageError=false;render();}
 else if(a==='retry-load'){ui.loading=false;const r=store.load(state);state=state.page==='G'&&r.ok?transition(state,{type:'LOAD_SUCCESS'}):r.state;render();}
 else if(a==='retry-refresh'){ui.reading=false;const r=store.load(state);if(r.ok)state=transition(r.state,{type:'REFRESH_SUCCESS'});else state=transition(state,{type:'REFRESH_ERROR'});render();}
 else if(a==='recover'){const r=store.recoverSubmission(state);if(r.event)state=transition(state,r.event);if(!state.submissionRecoveryRequired)persist();render();}
 else if(['retry-draft','draft-retry'].includes(a))saveDraft();
 else if(['retry-check','check-retry'].includes(a))submit();
 else if(a==='retry-persist'){persist();patch();}
 else if(a==='external-reload'){clearTimeout(sendTimer);clearTimeout(saveTimer);if(currentLetter(state)?.draft&&!confirm('重新读取会替换本页的未保存文字。请先复制保留文字，再继续读取。'))return;externalChange=false;const r=store.load(state);state=r.state;render();}
});
window.addEventListener('pagehide',()=>{if(!fixture&&!externalChange&&state.page==='G'&&state.replySubmitState!=='SUBMITTING'){const ta=app.querySelector('textarea');if(ta)state=transition(state,{type:'EDIT',value:ta.value});composing=false;saveDraft();}});
window.addEventListener('storage',ev=>{if(!fixture&&ev.key===STORAGE_KEY){clearTimeout(saveTimer);clearTimeout(sendTimer);externalChange=true;patch();}});
window.addEventListener('message',ev=>{if(ev.origin!==location.origin||ev.source!==parent||ev.data?.type!=='daily-review-action')return;const action=ev.data.action;
 if(action==='arrive-need')apply({type:'NEW_LETTER',letter:LETTER_FIXTURES['need-02']},{paint:state.page!=='G',save:true});
 if(action==='arrive-postcard')apply({type:'NEW_LETTER',letter:LETTER_FIXTURES['postcard-01']},{paint:state.page!=='G',save:true});
 if(action==='trip'||action==='home')apply({type:action==='trip'?'CAT_TRIP':'CAT_HOME'},{paint:state.page!=='G',save:true});
 if(action==='read-postcard'){const l=Object.values(state.letters).find(l=>l.type==='POSTCARD');if(l)apply({type:'POSTCARD_READ',letterId:l.id},{paint:state.page!=='G',save:true});}
 if(action==='old-draft'){const l=Object.values(state.letters).find(l=>l.type==='NEED_CARD'&&l.readState==='READ');if(l){ui.draftRestored=!!l.draft;apply({type:'OPEN_NEED',letterId:l.id},{save:true});}}
 if(action==='send-error')failures.sendError=1;if(action==='save-error')failures.draftError=1;if(action==='check-error')failures.checkError=1;if(action==='safety')failures.safetyBlocked=1;
 if(action==='refresh-error'){apply({type:state.page==='H'?'REFRESH_ERROR':'LOAD_ERROR'});}
 if(action==='reset'){clearTimeout(sendTimer);clearTimeout(saveTimer);failures={};const demoMemory=new Map();store=createDailyStore({storage:{getItem:k=>demoMemory.get(k)??null,setItem:(k,v)=>demoMemory.set(k,v),removeItem:k=>demoMemory.delete(k)}});state=initialState();ui={};externalChange=false;saveFailure=false;render();}
});
render();
